# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app

end

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'Firebase/Performance'
  pod 'Fabric'
  pod 'Crashlytics'


  # Pods for iosApp

  target 'iosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
